// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export class AccessList extends pulumi.CustomResource {
    /**
     * Get an existing AccessList resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: AccessListState, opts?: pulumi.CustomResourceOptions): AccessList {
        return new AccessList(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'teleport:index/accessList:AccessList';

    /**
     * Returns true if the given object is an instance of AccessList.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is AccessList {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === AccessList.__pulumiType;
    }

    /**
     * header is the header for the resource.
     */
    public readonly header!: pulumi.Output<outputs.AccessListHeader | undefined>;
    /**
     * spec is the specification for the Access List.
     */
    public readonly spec!: pulumi.Output<outputs.AccessListSpec | undefined>;

    /**
     * Create a AccessList resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: AccessListArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: AccessListArgs | AccessListState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as AccessListState | undefined;
            resourceInputs["header"] = state ? state.header : undefined;
            resourceInputs["spec"] = state ? state.spec : undefined;
        } else {
            const args = argsOrState as AccessListArgs | undefined;
            resourceInputs["header"] = args ? args.header : undefined;
            resourceInputs["spec"] = args ? args.spec : undefined;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(AccessList.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering AccessList resources.
 */
export interface AccessListState {
    /**
     * header is the header for the resource.
     */
    header?: pulumi.Input<inputs.AccessListHeader>;
    /**
     * spec is the specification for the Access List.
     */
    spec?: pulumi.Input<inputs.AccessListSpec>;
}

/**
 * The set of arguments for constructing a AccessList resource.
 */
export interface AccessListArgs {
    /**
     * header is the header for the resource.
     */
    header?: pulumi.Input<inputs.AccessListHeader>;
    /**
     * spec is the specification for the Access List.
     */
    spec?: pulumi.Input<inputs.AccessListSpec>;
}
