// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export class AccessMonitoringRule extends pulumi.CustomResource {
    /**
     * Get an existing AccessMonitoringRule resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: AccessMonitoringRuleState, opts?: pulumi.CustomResourceOptions): AccessMonitoringRule {
        return new AccessMonitoringRule(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'teleport:index/accessMonitoringRule:AccessMonitoringRule';

    /**
     * Returns true if the given object is an instance of AccessMonitoringRule.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is AccessMonitoringRule {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === AccessMonitoringRule.__pulumiType;
    }

    /**
     * kind is a resource kind
     */
    public readonly kind!: pulumi.Output<string>;
    /**
     * metadata is the rules's metadata.
     */
    public readonly metadata!: pulumi.Output<outputs.AccessMonitoringRuleMetadata | undefined>;
    /**
     * Spec is an AccessMonitoringRule specification
     */
    public readonly spec!: pulumi.Output<outputs.AccessMonitoringRuleSpec>;
    /**
     * sub_kind is an optional resource sub kind, used in some resources
     */
    public readonly subKind!: pulumi.Output<string | undefined>;
    /**
     * version is version
     */
    public readonly version!: pulumi.Output<string>;

    /**
     * Create a AccessMonitoringRule resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: AccessMonitoringRuleArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: AccessMonitoringRuleArgs | AccessMonitoringRuleState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as AccessMonitoringRuleState | undefined;
            resourceInputs["kind"] = state ? state.kind : undefined;
            resourceInputs["metadata"] = state ? state.metadata : undefined;
            resourceInputs["spec"] = state ? state.spec : undefined;
            resourceInputs["subKind"] = state ? state.subKind : undefined;
            resourceInputs["version"] = state ? state.version : undefined;
        } else {
            const args = argsOrState as AccessMonitoringRuleArgs | undefined;
            if ((!args || args.spec === undefined) && !opts.urn) {
                throw new Error("Missing required property 'spec'");
            }
            if ((!args || args.version === undefined) && !opts.urn) {
                throw new Error("Missing required property 'version'");
            }
            resourceInputs["kind"] = args ? args.kind : undefined;
            resourceInputs["metadata"] = args ? args.metadata : undefined;
            resourceInputs["spec"] = args ? args.spec : undefined;
            resourceInputs["subKind"] = args ? args.subKind : undefined;
            resourceInputs["version"] = args ? args.version : undefined;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(AccessMonitoringRule.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering AccessMonitoringRule resources.
 */
export interface AccessMonitoringRuleState {
    /**
     * kind is a resource kind
     */
    kind?: pulumi.Input<string>;
    /**
     * metadata is the rules's metadata.
     */
    metadata?: pulumi.Input<inputs.AccessMonitoringRuleMetadata>;
    /**
     * Spec is an AccessMonitoringRule specification
     */
    spec?: pulumi.Input<inputs.AccessMonitoringRuleSpec>;
    /**
     * sub_kind is an optional resource sub kind, used in some resources
     */
    subKind?: pulumi.Input<string>;
    /**
     * version is version
     */
    version?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a AccessMonitoringRule resource.
 */
export interface AccessMonitoringRuleArgs {
    /**
     * kind is a resource kind
     */
    kind?: pulumi.Input<string>;
    /**
     * metadata is the rules's metadata.
     */
    metadata?: pulumi.Input<inputs.AccessMonitoringRuleMetadata>;
    /**
     * Spec is an AccessMonitoringRule specification
     */
    spec: pulumi.Input<inputs.AccessMonitoringRuleSpec>;
    /**
     * sub_kind is an optional resource sub kind, used in some resources
     */
    subKind?: pulumi.Input<string>;
    /**
     * version is version
     */
    version: pulumi.Input<string>;
}
