// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export class AuthPreference extends pulumi.CustomResource {
    /**
     * Get an existing AuthPreference resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: AuthPreferenceState, opts?: pulumi.CustomResourceOptions): AuthPreference {
        return new AuthPreference(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'teleport:index/authPreference:AuthPreference';

    /**
     * Returns true if the given object is an instance of AuthPreference.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is AuthPreference {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === AuthPreference.__pulumiType;
    }

    /**
     * Kind is a resource kind
     */
    public readonly kind!: pulumi.Output<string>;
    /**
     * Metadata is resource metadata
     */
    public readonly metadata!: pulumi.Output<outputs.AuthPreferenceMetadata | undefined>;
    /**
     * Spec is an AuthPreference specification
     */
    public readonly spec!: pulumi.Output<outputs.AuthPreferenceSpec>;
    /**
     * SubKind is an optional resource sub kind, used in some resources
     */
    public readonly subKind!: pulumi.Output<string | undefined>;
    /**
     * Version is the resource version. It must be specified. Supported values are: `v2`.
     */
    public readonly version!: pulumi.Output<string>;

    /**
     * Create a AuthPreference resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: AuthPreferenceArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: AuthPreferenceArgs | AuthPreferenceState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as AuthPreferenceState | undefined;
            resourceInputs["kind"] = state ? state.kind : undefined;
            resourceInputs["metadata"] = state ? state.metadata : undefined;
            resourceInputs["spec"] = state ? state.spec : undefined;
            resourceInputs["subKind"] = state ? state.subKind : undefined;
            resourceInputs["version"] = state ? state.version : undefined;
        } else {
            const args = argsOrState as AuthPreferenceArgs | undefined;
            if ((!args || args.spec === undefined) && !opts.urn) {
                throw new Error("Missing required property 'spec'");
            }
            if ((!args || args.version === undefined) && !opts.urn) {
                throw new Error("Missing required property 'version'");
            }
            resourceInputs["kind"] = args ? args.kind : undefined;
            resourceInputs["metadata"] = args ? args.metadata : undefined;
            resourceInputs["spec"] = args ? args.spec : undefined;
            resourceInputs["subKind"] = args ? args.subKind : undefined;
            resourceInputs["version"] = args ? args.version : undefined;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(AuthPreference.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering AuthPreference resources.
 */
export interface AuthPreferenceState {
    /**
     * Kind is a resource kind
     */
    kind?: pulumi.Input<string>;
    /**
     * Metadata is resource metadata
     */
    metadata?: pulumi.Input<inputs.AuthPreferenceMetadata>;
    /**
     * Spec is an AuthPreference specification
     */
    spec?: pulumi.Input<inputs.AuthPreferenceSpec>;
    /**
     * SubKind is an optional resource sub kind, used in some resources
     */
    subKind?: pulumi.Input<string>;
    /**
     * Version is the resource version. It must be specified. Supported values are: `v2`.
     */
    version?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a AuthPreference resource.
 */
export interface AuthPreferenceArgs {
    /**
     * Kind is a resource kind
     */
    kind?: pulumi.Input<string>;
    /**
     * Metadata is resource metadata
     */
    metadata?: pulumi.Input<inputs.AuthPreferenceMetadata>;
    /**
     * Spec is an AuthPreference specification
     */
    spec: pulumi.Input<inputs.AuthPreferenceSpec>;
    /**
     * SubKind is an optional resource sub kind, used in some resources
     */
    subKind?: pulumi.Input<string>;
    /**
     * Version is the resource version. It must be specified. Supported values are: `v2`.
     */
    version: pulumi.Input<string>;
}
