// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export class ClusterNetworkingConfig extends pulumi.CustomResource {
    /**
     * Get an existing ClusterNetworkingConfig resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: ClusterNetworkingConfigState, opts?: pulumi.CustomResourceOptions): ClusterNetworkingConfig {
        return new ClusterNetworkingConfig(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'teleport:index/clusterNetworkingConfig:ClusterNetworkingConfig';

    /**
     * Returns true if the given object is an instance of ClusterNetworkingConfig.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is ClusterNetworkingConfig {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === ClusterNetworkingConfig.__pulumiType;
    }

    /**
     * Kind is a resource kind
     */
    public readonly kind!: pulumi.Output<string>;
    /**
     * Metadata is resource metadata
     */
    public readonly metadata!: pulumi.Output<outputs.ClusterNetworkingConfigMetadata | undefined>;
    /**
     * Spec is a ClusterNetworkingConfig specification
     */
    public readonly spec!: pulumi.Output<outputs.ClusterNetworkingConfigSpec | undefined>;
    /**
     * SubKind is an optional resource sub kind, used in some resources
     */
    public readonly subKind!: pulumi.Output<string | undefined>;
    /**
     * Version is the resource version. It must be specified. Supported values are:`v2`.
     */
    public readonly version!: pulumi.Output<string>;

    /**
     * Create a ClusterNetworkingConfig resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: ClusterNetworkingConfigArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: ClusterNetworkingConfigArgs | ClusterNetworkingConfigState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as ClusterNetworkingConfigState | undefined;
            resourceInputs["kind"] = state ? state.kind : undefined;
            resourceInputs["metadata"] = state ? state.metadata : undefined;
            resourceInputs["spec"] = state ? state.spec : undefined;
            resourceInputs["subKind"] = state ? state.subKind : undefined;
            resourceInputs["version"] = state ? state.version : undefined;
        } else {
            const args = argsOrState as ClusterNetworkingConfigArgs | undefined;
            resourceInputs["kind"] = args ? args.kind : undefined;
            resourceInputs["metadata"] = args ? args.metadata : undefined;
            resourceInputs["spec"] = args ? args.spec : undefined;
            resourceInputs["subKind"] = args ? args.subKind : undefined;
            resourceInputs["version"] = args ? args.version : undefined;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(ClusterNetworkingConfig.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering ClusterNetworkingConfig resources.
 */
export interface ClusterNetworkingConfigState {
    /**
     * Kind is a resource kind
     */
    kind?: pulumi.Input<string>;
    /**
     * Metadata is resource metadata
     */
    metadata?: pulumi.Input<inputs.ClusterNetworkingConfigMetadata>;
    /**
     * Spec is a ClusterNetworkingConfig specification
     */
    spec?: pulumi.Input<inputs.ClusterNetworkingConfigSpec>;
    /**
     * SubKind is an optional resource sub kind, used in some resources
     */
    subKind?: pulumi.Input<string>;
    /**
     * Version is the resource version. It must be specified. Supported values are:`v2`.
     */
    version?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a ClusterNetworkingConfig resource.
 */
export interface ClusterNetworkingConfigArgs {
    /**
     * Kind is a resource kind
     */
    kind?: pulumi.Input<string>;
    /**
     * Metadata is resource metadata
     */
    metadata?: pulumi.Input<inputs.ClusterNetworkingConfigMetadata>;
    /**
     * Spec is a ClusterNetworkingConfig specification
     */
    spec?: pulumi.Input<inputs.ClusterNetworkingConfigSpec>;
    /**
     * SubKind is an optional resource sub kind, used in some resources
     */
    subKind?: pulumi.Input<string>;
    /**
     * Version is the resource version. It must be specified. Supported values are:`v2`.
     */
    version?: pulumi.Input<string>;
}
