// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export class ClusterMaintenanceConfig extends pulumi.CustomResource {
    /**
     * Get an existing ClusterMaintenanceConfig resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: ClusterMaintenanceConfigState, opts?: pulumi.CustomResourceOptions): ClusterMaintenanceConfig {
        return new ClusterMaintenanceConfig(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'teleport:index/clusterMaintenanceConfig:ClusterMaintenanceConfig';

    /**
     * Returns true if the given object is an instance of ClusterMaintenanceConfig.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is ClusterMaintenanceConfig {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === ClusterMaintenanceConfig.__pulumiType;
    }

    /**
     * Kind is a resource kind
     */
    public readonly kind!: pulumi.Output<string>;
    /**
     * Metadata is resource metadata
     */
    public readonly metadata!: pulumi.Output<outputs.ClusterMaintenanceConfigMetadata | undefined>;
    /**
     * Nonce is used to protect against concurrent modification of the maintenance window. Clients should treat nonces as
     * opaque.
     */
    public readonly nonce!: pulumi.Output<number | undefined>;
    public readonly spec!: pulumi.Output<outputs.ClusterMaintenanceConfigSpec | undefined>;
    /**
     * SubKind is an optional resource sub kind, used in some resources
     */
    public readonly subKind!: pulumi.Output<string | undefined>;
    /**
     * Version is the API version used to create the resource. It must be specified. Based on this version, Teleport will apply
     * different defaults on resource creation or deletion. It must be an integer prefixed by "v". For example: `v1`
     */
    public readonly version!: pulumi.Output<string>;

    /**
     * Create a ClusterMaintenanceConfig resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: ClusterMaintenanceConfigArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: ClusterMaintenanceConfigArgs | ClusterMaintenanceConfigState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as ClusterMaintenanceConfigState | undefined;
            resourceInputs["kind"] = state ? state.kind : undefined;
            resourceInputs["metadata"] = state ? state.metadata : undefined;
            resourceInputs["nonce"] = state ? state.nonce : undefined;
            resourceInputs["spec"] = state ? state.spec : undefined;
            resourceInputs["subKind"] = state ? state.subKind : undefined;
            resourceInputs["version"] = state ? state.version : undefined;
        } else {
            const args = argsOrState as ClusterMaintenanceConfigArgs | undefined;
            if ((!args || args.version === undefined) && !opts.urn) {
                throw new Error("Missing required property 'version'");
            }
            resourceInputs["kind"] = args ? args.kind : undefined;
            resourceInputs["metadata"] = args ? args.metadata : undefined;
            resourceInputs["nonce"] = args ? args.nonce : undefined;
            resourceInputs["spec"] = args ? args.spec : undefined;
            resourceInputs["subKind"] = args ? args.subKind : undefined;
            resourceInputs["version"] = args ? args.version : undefined;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(ClusterMaintenanceConfig.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering ClusterMaintenanceConfig resources.
 */
export interface ClusterMaintenanceConfigState {
    /**
     * Kind is a resource kind
     */
    kind?: pulumi.Input<string>;
    /**
     * Metadata is resource metadata
     */
    metadata?: pulumi.Input<inputs.ClusterMaintenanceConfigMetadata>;
    /**
     * Nonce is used to protect against concurrent modification of the maintenance window. Clients should treat nonces as
     * opaque.
     */
    nonce?: pulumi.Input<number>;
    spec?: pulumi.Input<inputs.ClusterMaintenanceConfigSpec>;
    /**
     * SubKind is an optional resource sub kind, used in some resources
     */
    subKind?: pulumi.Input<string>;
    /**
     * Version is the API version used to create the resource. It must be specified. Based on this version, Teleport will apply
     * different defaults on resource creation or deletion. It must be an integer prefixed by "v". For example: `v1`
     */
    version?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a ClusterMaintenanceConfig resource.
 */
export interface ClusterMaintenanceConfigArgs {
    /**
     * Kind is a resource kind
     */
    kind?: pulumi.Input<string>;
    /**
     * Metadata is resource metadata
     */
    metadata?: pulumi.Input<inputs.ClusterMaintenanceConfigMetadata>;
    /**
     * Nonce is used to protect against concurrent modification of the maintenance window. Clients should treat nonces as
     * opaque.
     */
    nonce?: pulumi.Input<number>;
    spec?: pulumi.Input<inputs.ClusterMaintenanceConfigSpec>;
    /**
     * SubKind is an optional resource sub kind, used in some resources
     */
    subKind?: pulumi.Input<string>;
    /**
     * Version is the API version used to create the resource. It must be specified. Based on this version, Teleport will apply
     * different defaults on resource creation or deletion. It must be an integer prefixed by "v". For example: `v1`
     */
    version: pulumi.Input<string>;
}
