// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getAutoupdateVersion(args: GetAutoupdateVersionArgs, opts?: pulumi.InvokeOptions): Promise<GetAutoupdateVersionResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("teleport:index/getAutoupdateVersion:getAutoupdateVersion", {
        "kind": args.kind,
        "metadata": args.metadata,
        "spec": args.spec,
        "subKind": args.subKind,
        "version": args.version,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getAutoupdateVersion.
 */
export interface GetAutoupdateVersionArgs {
    kind?: string;
    metadata?: inputs.GetAutoupdateVersionMetadata;
    spec: inputs.GetAutoupdateVersionSpec;
    subKind?: string;
    version: string;
}

/**
 * A collection of values returned by getAutoupdateVersion.
 */
export interface GetAutoupdateVersionResult {
    readonly id: string;
    readonly kind: string;
    readonly metadata: outputs.GetAutoupdateVersionMetadata;
    readonly spec: outputs.GetAutoupdateVersionSpec;
    readonly subKind?: string;
    readonly version: string;
}
export function getAutoupdateVersionOutput(args: GetAutoupdateVersionOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetAutoupdateVersionResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("teleport:index/getAutoupdateVersion:getAutoupdateVersion", {
        "kind": args.kind,
        "metadata": args.metadata,
        "spec": args.spec,
        "subKind": args.subKind,
        "version": args.version,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getAutoupdateVersion.
 */
export interface GetAutoupdateVersionOutputArgs {
    kind?: pulumi.Input<string>;
    metadata?: pulumi.Input<inputs.GetAutoupdateVersionMetadataArgs>;
    spec: pulumi.Input<inputs.GetAutoupdateVersionSpecArgs>;
    subKind?: pulumi.Input<string>;
    version: pulumi.Input<string>;
}
