// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getAccessMonitoringRule(args: GetAccessMonitoringRuleArgs, opts?: pulumi.InvokeOptions): Promise<GetAccessMonitoringRuleResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("teleport:index/getAccessMonitoringRule:getAccessMonitoringRule", {
        "kind": args.kind,
        "metadata": args.metadata,
        "spec": args.spec,
        "subKind": args.subKind,
        "version": args.version,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getAccessMonitoringRule.
 */
export interface GetAccessMonitoringRuleArgs {
    kind?: string;
    metadata?: inputs.GetAccessMonitoringRuleMetadata;
    spec: inputs.GetAccessMonitoringRuleSpec;
    subKind?: string;
    version: string;
}

/**
 * A collection of values returned by getAccessMonitoringRule.
 */
export interface GetAccessMonitoringRuleResult {
    readonly id: string;
    readonly kind: string;
    readonly metadata?: outputs.GetAccessMonitoringRuleMetadata;
    readonly spec: outputs.GetAccessMonitoringRuleSpec;
    readonly subKind?: string;
    readonly version: string;
}
export function getAccessMonitoringRuleOutput(args: GetAccessMonitoringRuleOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetAccessMonitoringRuleResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("teleport:index/getAccessMonitoringRule:getAccessMonitoringRule", {
        "kind": args.kind,
        "metadata": args.metadata,
        "spec": args.spec,
        "subKind": args.subKind,
        "version": args.version,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getAccessMonitoringRule.
 */
export interface GetAccessMonitoringRuleOutputArgs {
    kind?: pulumi.Input<string>;
    metadata?: pulumi.Input<inputs.GetAccessMonitoringRuleMetadataArgs>;
    spec: pulumi.Input<inputs.GetAccessMonitoringRuleSpecArgs>;
    subKind?: pulumi.Input<string>;
    version: pulumi.Input<string>;
}
