// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getApp(args: GetAppArgs, opts?: pulumi.InvokeOptions): Promise<GetAppResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("teleport:index/getApp:getApp", {
        "kind": args.kind,
        "metadata": args.metadata,
        "spec": args.spec,
        "subKind": args.subKind,
        "version": args.version,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getApp.
 */
export interface GetAppArgs {
    kind?: string;
    metadata?: inputs.GetAppMetadata;
    spec?: inputs.GetAppSpec;
    subKind?: string;
    version: string;
}

/**
 * A collection of values returned by getApp.
 */
export interface GetAppResult {
    readonly id: string;
    readonly kind: string;
    readonly metadata?: outputs.GetAppMetadata;
    readonly spec?: outputs.GetAppSpec;
    readonly subKind?: string;
    readonly version: string;
}
export function getAppOutput(args: GetAppOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetAppResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("teleport:index/getApp:getApp", {
        "kind": args.kind,
        "metadata": args.metadata,
        "spec": args.spec,
        "subKind": args.subKind,
        "version": args.version,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getApp.
 */
export interface GetAppOutputArgs {
    kind?: pulumi.Input<string>;
    metadata?: pulumi.Input<inputs.GetAppMetadataArgs>;
    spec?: pulumi.Input<inputs.GetAppSpecArgs>;
    subKind?: pulumi.Input<string>;
    version: pulumi.Input<string>;
}
