// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getAutoupdateConfig(args: GetAutoupdateConfigArgs, opts?: pulumi.InvokeOptions): Promise<GetAutoupdateConfigResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("teleport:index/getAutoupdateConfig:getAutoupdateConfig", {
        "kind": args.kind,
        "metadata": args.metadata,
        "spec": args.spec,
        "subKind": args.subKind,
        "version": args.version,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getAutoupdateConfig.
 */
export interface GetAutoupdateConfigArgs {
    kind?: string;
    metadata?: inputs.GetAutoupdateConfigMetadata;
    spec: inputs.GetAutoupdateConfigSpec;
    subKind?: string;
    version: string;
}

/**
 * A collection of values returned by getAutoupdateConfig.
 */
export interface GetAutoupdateConfigResult {
    readonly id: string;
    readonly kind: string;
    readonly metadata: outputs.GetAutoupdateConfigMetadata;
    readonly spec: outputs.GetAutoupdateConfigSpec;
    readonly subKind?: string;
    readonly version: string;
}
export function getAutoupdateConfigOutput(args: GetAutoupdateConfigOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetAutoupdateConfigResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("teleport:index/getAutoupdateConfig:getAutoupdateConfig", {
        "kind": args.kind,
        "metadata": args.metadata,
        "spec": args.spec,
        "subKind": args.subKind,
        "version": args.version,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getAutoupdateConfig.
 */
export interface GetAutoupdateConfigOutputArgs {
    kind?: pulumi.Input<string>;
    metadata?: pulumi.Input<inputs.GetAutoupdateConfigMetadataArgs>;
    spec: pulumi.Input<inputs.GetAutoupdateConfigSpecArgs>;
    subKind?: pulumi.Input<string>;
    version: pulumi.Input<string>;
}
