// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getAuthPreference(args: GetAuthPreferenceArgs, opts?: pulumi.InvokeOptions): Promise<GetAuthPreferenceResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("teleport:index/getAuthPreference:getAuthPreference", {
        "kind": args.kind,
        "metadata": args.metadata,
        "spec": args.spec,
        "subKind": args.subKind,
        "version": args.version,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getAuthPreference.
 */
export interface GetAuthPreferenceArgs {
    kind?: string;
    metadata?: inputs.GetAuthPreferenceMetadata;
    spec: inputs.GetAuthPreferenceSpec;
    subKind?: string;
    version: string;
}

/**
 * A collection of values returned by getAuthPreference.
 */
export interface GetAuthPreferenceResult {
    readonly id: string;
    readonly kind: string;
    readonly metadata?: outputs.GetAuthPreferenceMetadata;
    readonly spec: outputs.GetAuthPreferenceSpec;
    readonly subKind?: string;
    readonly version: string;
}
export function getAuthPreferenceOutput(args: GetAuthPreferenceOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetAuthPreferenceResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("teleport:index/getAuthPreference:getAuthPreference", {
        "kind": args.kind,
        "metadata": args.metadata,
        "spec": args.spec,
        "subKind": args.subKind,
        "version": args.version,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getAuthPreference.
 */
export interface GetAuthPreferenceOutputArgs {
    kind?: pulumi.Input<string>;
    metadata?: pulumi.Input<inputs.GetAuthPreferenceMetadataArgs>;
    spec: pulumi.Input<inputs.GetAuthPreferenceSpecArgs>;
    subKind?: pulumi.Input<string>;
    version: pulumi.Input<string>;
}
