// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getClusterMaintenanceConfig(args: GetClusterMaintenanceConfigArgs, opts?: pulumi.InvokeOptions): Promise<GetClusterMaintenanceConfigResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("teleport:index/getClusterMaintenanceConfig:getClusterMaintenanceConfig", {
        "kind": args.kind,
        "metadata": args.metadata,
        "nonce": args.nonce,
        "spec": args.spec,
        "subKind": args.subKind,
        "version": args.version,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getClusterMaintenanceConfig.
 */
export interface GetClusterMaintenanceConfigArgs {
    kind?: string;
    metadata?: inputs.GetClusterMaintenanceConfigMetadata;
    nonce?: number;
    spec?: inputs.GetClusterMaintenanceConfigSpec;
    subKind?: string;
    version: string;
}

/**
 * A collection of values returned by getClusterMaintenanceConfig.
 */
export interface GetClusterMaintenanceConfigResult {
    readonly id: string;
    readonly kind: string;
    readonly metadata?: outputs.GetClusterMaintenanceConfigMetadata;
    readonly nonce?: number;
    readonly spec?: outputs.GetClusterMaintenanceConfigSpec;
    readonly subKind?: string;
    readonly version: string;
}
export function getClusterMaintenanceConfigOutput(args: GetClusterMaintenanceConfigOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetClusterMaintenanceConfigResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("teleport:index/getClusterMaintenanceConfig:getClusterMaintenanceConfig", {
        "kind": args.kind,
        "metadata": args.metadata,
        "nonce": args.nonce,
        "spec": args.spec,
        "subKind": args.subKind,
        "version": args.version,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getClusterMaintenanceConfig.
 */
export interface GetClusterMaintenanceConfigOutputArgs {
    kind?: pulumi.Input<string>;
    metadata?: pulumi.Input<inputs.GetClusterMaintenanceConfigMetadataArgs>;
    nonce?: pulumi.Input<number>;
    spec?: pulumi.Input<inputs.GetClusterMaintenanceConfigSpecArgs>;
    subKind?: pulumi.Input<string>;
    version: pulumi.Input<string>;
}
