// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getClusterNetworkingConfig(args?: GetClusterNetworkingConfigArgs, opts?: pulumi.InvokeOptions): Promise<GetClusterNetworkingConfigResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("teleport:index/getClusterNetworkingConfig:getClusterNetworkingConfig", {
        "kind": args.kind,
        "metadata": args.metadata,
        "spec": args.spec,
        "subKind": args.subKind,
        "version": args.version,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getClusterNetworkingConfig.
 */
export interface GetClusterNetworkingConfigArgs {
    kind?: string;
    metadata?: inputs.GetClusterNetworkingConfigMetadata;
    spec?: inputs.GetClusterNetworkingConfigSpec;
    subKind?: string;
    version?: string;
}

/**
 * A collection of values returned by getClusterNetworkingConfig.
 */
export interface GetClusterNetworkingConfigResult {
    readonly id: string;
    readonly kind: string;
    readonly metadata?: outputs.GetClusterNetworkingConfigMetadata;
    readonly spec?: outputs.GetClusterNetworkingConfigSpec;
    readonly subKind?: string;
    readonly version: string;
}
export function getClusterNetworkingConfigOutput(args?: GetClusterNetworkingConfigOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetClusterNetworkingConfigResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("teleport:index/getClusterNetworkingConfig:getClusterNetworkingConfig", {
        "kind": args.kind,
        "metadata": args.metadata,
        "spec": args.spec,
        "subKind": args.subKind,
        "version": args.version,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getClusterNetworkingConfig.
 */
export interface GetClusterNetworkingConfigOutputArgs {
    kind?: pulumi.Input<string>;
    metadata?: pulumi.Input<inputs.GetClusterNetworkingConfigMetadataArgs>;
    spec?: pulumi.Input<inputs.GetClusterNetworkingConfigSpecArgs>;
    subKind?: pulumi.Input<string>;
    version?: pulumi.Input<string>;
}
