// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getDynamicWindowsDesktop(args: GetDynamicWindowsDesktopArgs, opts?: pulumi.InvokeOptions): Promise<GetDynamicWindowsDesktopResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("teleport:index/getDynamicWindowsDesktop:getDynamicWindowsDesktop", {
        "kind": args.kind,
        "metadata": args.metadata,
        "spec": args.spec,
        "subKind": args.subKind,
        "version": args.version,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getDynamicWindowsDesktop.
 */
export interface GetDynamicWindowsDesktopArgs {
    kind?: string;
    metadata?: inputs.GetDynamicWindowsDesktopMetadata;
    spec: inputs.GetDynamicWindowsDesktopSpec;
    subKind?: string;
    version: string;
}

/**
 * A collection of values returned by getDynamicWindowsDesktop.
 */
export interface GetDynamicWindowsDesktopResult {
    readonly id: string;
    readonly kind: string;
    readonly metadata?: outputs.GetDynamicWindowsDesktopMetadata;
    readonly spec: outputs.GetDynamicWindowsDesktopSpec;
    readonly subKind?: string;
    readonly version: string;
}
export function getDynamicWindowsDesktopOutput(args: GetDynamicWindowsDesktopOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetDynamicWindowsDesktopResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("teleport:index/getDynamicWindowsDesktop:getDynamicWindowsDesktop", {
        "kind": args.kind,
        "metadata": args.metadata,
        "spec": args.spec,
        "subKind": args.subKind,
        "version": args.version,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getDynamicWindowsDesktop.
 */
export interface GetDynamicWindowsDesktopOutputArgs {
    kind?: pulumi.Input<string>;
    metadata?: pulumi.Input<inputs.GetDynamicWindowsDesktopMetadataArgs>;
    spec: pulumi.Input<inputs.GetDynamicWindowsDesktopSpecArgs>;
    subKind?: pulumi.Input<string>;
    version: pulumi.Input<string>;
}
