// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getGithubConnector(args: GetGithubConnectorArgs, opts?: pulumi.InvokeOptions): Promise<GetGithubConnectorResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("teleport:index/getGithubConnector:getGithubConnector", {
        "kind": args.kind,
        "metadata": args.metadata,
        "spec": args.spec,
        "subKind": args.subKind,
        "version": args.version,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getGithubConnector.
 */
export interface GetGithubConnectorArgs {
    kind?: string;
    metadata?: inputs.GetGithubConnectorMetadata;
    spec: inputs.GetGithubConnectorSpec;
    subKind?: string;
    version: string;
}

/**
 * A collection of values returned by getGithubConnector.
 */
export interface GetGithubConnectorResult {
    readonly id: string;
    readonly kind: string;
    readonly metadata?: outputs.GetGithubConnectorMetadata;
    readonly spec: outputs.GetGithubConnectorSpec;
    readonly subKind?: string;
    readonly version: string;
}
export function getGithubConnectorOutput(args: GetGithubConnectorOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetGithubConnectorResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("teleport:index/getGithubConnector:getGithubConnector", {
        "kind": args.kind,
        "metadata": args.metadata,
        "spec": args.spec,
        "subKind": args.subKind,
        "version": args.version,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getGithubConnector.
 */
export interface GetGithubConnectorOutputArgs {
    kind?: pulumi.Input<string>;
    metadata?: pulumi.Input<inputs.GetGithubConnectorMetadataArgs>;
    spec: pulumi.Input<inputs.GetGithubConnectorSpecArgs>;
    subKind?: pulumi.Input<string>;
    version: pulumi.Input<string>;
}
