// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getInstaller(args: GetInstallerArgs, opts?: pulumi.InvokeOptions): Promise<GetInstallerResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("teleport:index/getInstaller:getInstaller", {
        "kind": args.kind,
        "metadata": args.metadata,
        "spec": args.spec,
        "subKind": args.subKind,
        "version": args.version,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getInstaller.
 */
export interface GetInstallerArgs {
    kind?: string;
    metadata?: inputs.GetInstallerMetadata;
    spec: inputs.GetInstallerSpec;
    subKind?: string;
    version: string;
}

/**
 * A collection of values returned by getInstaller.
 */
export interface GetInstallerResult {
    readonly id: string;
    readonly kind: string;
    readonly metadata?: outputs.GetInstallerMetadata;
    readonly spec: outputs.GetInstallerSpec;
    readonly subKind?: string;
    readonly version: string;
}
export function getInstallerOutput(args: GetInstallerOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetInstallerResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("teleport:index/getInstaller:getInstaller", {
        "kind": args.kind,
        "metadata": args.metadata,
        "spec": args.spec,
        "subKind": args.subKind,
        "version": args.version,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getInstaller.
 */
export interface GetInstallerOutputArgs {
    kind?: pulumi.Input<string>;
    metadata?: pulumi.Input<inputs.GetInstallerMetadataArgs>;
    spec: pulumi.Input<inputs.GetInstallerSpecArgs>;
    subKind?: pulumi.Input<string>;
    version: pulumi.Input<string>;
}
