// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getLoginRule(args: GetLoginRuleArgs, opts?: pulumi.InvokeOptions): Promise<GetLoginRuleResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("teleport:index/getLoginRule:getLoginRule", {
        "metadata": args.metadata,
        "priority": args.priority,
        "traitsExpression": args.traitsExpression,
        "traitsMap": args.traitsMap,
        "version": args.version,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getLoginRule.
 */
export interface GetLoginRuleArgs {
    metadata?: inputs.GetLoginRuleMetadata;
    priority: number;
    traitsExpression?: string;
    traitsMap?: {[key: string]: inputs.GetLoginRuleTraitsMap};
    version: string;
}

/**
 * A collection of values returned by getLoginRule.
 */
export interface GetLoginRuleResult {
    readonly id: string;
    readonly metadata?: outputs.GetLoginRuleMetadata;
    readonly priority: number;
    readonly traitsExpression?: string;
    readonly traitsMap?: {[key: string]: outputs.GetLoginRuleTraitsMap};
    readonly version: string;
}
export function getLoginRuleOutput(args: GetLoginRuleOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetLoginRuleResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("teleport:index/getLoginRule:getLoginRule", {
        "metadata": args.metadata,
        "priority": args.priority,
        "traitsExpression": args.traitsExpression,
        "traitsMap": args.traitsMap,
        "version": args.version,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getLoginRule.
 */
export interface GetLoginRuleOutputArgs {
    metadata?: pulumi.Input<inputs.GetLoginRuleMetadataArgs>;
    priority: pulumi.Input<number>;
    traitsExpression?: pulumi.Input<string>;
    traitsMap?: pulumi.Input<{[key: string]: pulumi.Input<inputs.GetLoginRuleTraitsMapArgs>}>;
    version: pulumi.Input<string>;
}
