// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getOidcConnector(args: GetOidcConnectorArgs, opts?: pulumi.InvokeOptions): Promise<GetOidcConnectorResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("teleport:index/getOidcConnector:getOidcConnector", {
        "kind": args.kind,
        "metadata": args.metadata,
        "spec": args.spec,
        "subKind": args.subKind,
        "version": args.version,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getOidcConnector.
 */
export interface GetOidcConnectorArgs {
    kind?: string;
    metadata?: inputs.GetOidcConnectorMetadata;
    spec: inputs.GetOidcConnectorSpec;
    subKind?: string;
    version: string;
}

/**
 * A collection of values returned by getOidcConnector.
 */
export interface GetOidcConnectorResult {
    readonly id: string;
    readonly kind: string;
    readonly metadata?: outputs.GetOidcConnectorMetadata;
    readonly spec: outputs.GetOidcConnectorSpec;
    readonly subKind?: string;
    readonly version: string;
}
export function getOidcConnectorOutput(args: GetOidcConnectorOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetOidcConnectorResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("teleport:index/getOidcConnector:getOidcConnector", {
        "kind": args.kind,
        "metadata": args.metadata,
        "spec": args.spec,
        "subKind": args.subKind,
        "version": args.version,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getOidcConnector.
 */
export interface GetOidcConnectorOutputArgs {
    kind?: pulumi.Input<string>;
    metadata?: pulumi.Input<inputs.GetOidcConnectorMetadataArgs>;
    spec: pulumi.Input<inputs.GetOidcConnectorSpecArgs>;
    subKind?: pulumi.Input<string>;
    version: pulumi.Input<string>;
}
