// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getOktaImportRule(args: GetOktaImportRuleArgs, opts?: pulumi.InvokeOptions): Promise<GetOktaImportRuleResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("teleport:index/getOktaImportRule:getOktaImportRule", {
        "kind": args.kind,
        "metadata": args.metadata,
        "spec": args.spec,
        "subKind": args.subKind,
        "version": args.version,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getOktaImportRule.
 */
export interface GetOktaImportRuleArgs {
    kind?: string;
    metadata?: inputs.GetOktaImportRuleMetadata;
    spec: inputs.GetOktaImportRuleSpec;
    subKind?: string;
    version: string;
}

/**
 * A collection of values returned by getOktaImportRule.
 */
export interface GetOktaImportRuleResult {
    readonly id: string;
    readonly kind: string;
    readonly metadata?: outputs.GetOktaImportRuleMetadata;
    readonly spec: outputs.GetOktaImportRuleSpec;
    readonly subKind?: string;
    readonly version: string;
}
export function getOktaImportRuleOutput(args: GetOktaImportRuleOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetOktaImportRuleResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("teleport:index/getOktaImportRule:getOktaImportRule", {
        "kind": args.kind,
        "metadata": args.metadata,
        "spec": args.spec,
        "subKind": args.subKind,
        "version": args.version,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getOktaImportRule.
 */
export interface GetOktaImportRuleOutputArgs {
    kind?: pulumi.Input<string>;
    metadata?: pulumi.Input<inputs.GetOktaImportRuleMetadataArgs>;
    spec: pulumi.Input<inputs.GetOktaImportRuleSpecArgs>;
    subKind?: pulumi.Input<string>;
    version: pulumi.Input<string>;
}
