// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getProvisionToken(args: GetProvisionTokenArgs, opts?: pulumi.InvokeOptions): Promise<GetProvisionTokenResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("teleport:index/getProvisionToken:getProvisionToken", {
        "kind": args.kind,
        "metadata": args.metadata,
        "spec": args.spec,
        "subKind": args.subKind,
        "version": args.version,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getProvisionToken.
 */
export interface GetProvisionTokenArgs {
    kind?: string;
    metadata?: inputs.GetProvisionTokenMetadata;
    spec: inputs.GetProvisionTokenSpec;
    subKind?: string;
    version: string;
}

/**
 * A collection of values returned by getProvisionToken.
 */
export interface GetProvisionTokenResult {
    readonly id: string;
    readonly kind: string;
    readonly metadata?: outputs.GetProvisionTokenMetadata;
    readonly spec: outputs.GetProvisionTokenSpec;
    readonly subKind?: string;
    readonly version: string;
}
export function getProvisionTokenOutput(args: GetProvisionTokenOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetProvisionTokenResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("teleport:index/getProvisionToken:getProvisionToken", {
        "kind": args.kind,
        "metadata": args.metadata,
        "spec": args.spec,
        "subKind": args.subKind,
        "version": args.version,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getProvisionToken.
 */
export interface GetProvisionTokenOutputArgs {
    kind?: pulumi.Input<string>;
    metadata?: pulumi.Input<inputs.GetProvisionTokenMetadataArgs>;
    spec: pulumi.Input<inputs.GetProvisionTokenSpecArgs>;
    subKind?: pulumi.Input<string>;
    version: pulumi.Input<string>;
}
