// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getRole(args: GetRoleArgs, opts?: pulumi.InvokeOptions): Promise<GetRoleResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("teleport:index/getRole:getRole", {
        "kind": args.kind,
        "metadata": args.metadata,
        "spec": args.spec,
        "subKind": args.subKind,
        "version": args.version,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getRole.
 */
export interface GetRoleArgs {
    kind?: string;
    metadata?: inputs.GetRoleMetadata;
    spec?: inputs.GetRoleSpec;
    subKind?: string;
    version: string;
}

/**
 * A collection of values returned by getRole.
 */
export interface GetRoleResult {
    readonly id: string;
    readonly kind: string;
    readonly metadata?: outputs.GetRoleMetadata;
    readonly spec?: outputs.GetRoleSpec;
    readonly subKind?: string;
    readonly version: string;
}
export function getRoleOutput(args: GetRoleOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetRoleResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("teleport:index/getRole:getRole", {
        "kind": args.kind,
        "metadata": args.metadata,
        "spec": args.spec,
        "subKind": args.subKind,
        "version": args.version,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getRole.
 */
export interface GetRoleOutputArgs {
    kind?: pulumi.Input<string>;
    metadata?: pulumi.Input<inputs.GetRoleMetadataArgs>;
    spec?: pulumi.Input<inputs.GetRoleSpecArgs>;
    subKind?: pulumi.Input<string>;
    version: pulumi.Input<string>;
}
