// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getStaticHostUser(args: GetStaticHostUserArgs, opts?: pulumi.InvokeOptions): Promise<GetStaticHostUserResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("teleport:index/getStaticHostUser:getStaticHostUser", {
        "kind": args.kind,
        "metadata": args.metadata,
        "spec": args.spec,
        "subKind": args.subKind,
        "version": args.version,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getStaticHostUser.
 */
export interface GetStaticHostUserArgs {
    kind?: string;
    metadata: inputs.GetStaticHostUserMetadata;
    spec: inputs.GetStaticHostUserSpec;
    subKind?: string;
    version: string;
}

/**
 * A collection of values returned by getStaticHostUser.
 */
export interface GetStaticHostUserResult {
    readonly id: string;
    readonly kind: string;
    readonly metadata: outputs.GetStaticHostUserMetadata;
    readonly spec: outputs.GetStaticHostUserSpec;
    readonly subKind?: string;
    readonly version: string;
}
export function getStaticHostUserOutput(args: GetStaticHostUserOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetStaticHostUserResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("teleport:index/getStaticHostUser:getStaticHostUser", {
        "kind": args.kind,
        "metadata": args.metadata,
        "spec": args.spec,
        "subKind": args.subKind,
        "version": args.version,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getStaticHostUser.
 */
export interface GetStaticHostUserOutputArgs {
    kind?: pulumi.Input<string>;
    metadata: pulumi.Input<inputs.GetStaticHostUserMetadataArgs>;
    spec: pulumi.Input<inputs.GetStaticHostUserSpecArgs>;
    subKind?: pulumi.Input<string>;
    version: pulumi.Input<string>;
}
