// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getSessionRecordingConfig(args: GetSessionRecordingConfigArgs, opts?: pulumi.InvokeOptions): Promise<GetSessionRecordingConfigResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("teleport:index/getSessionRecordingConfig:getSessionRecordingConfig", {
        "kind": args.kind,
        "metadata": args.metadata,
        "spec": args.spec,
        "subKind": args.subKind,
        "version": args.version,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSessionRecordingConfig.
 */
export interface GetSessionRecordingConfigArgs {
    kind?: string;
    metadata?: inputs.GetSessionRecordingConfigMetadata;
    spec?: inputs.GetSessionRecordingConfigSpec;
    subKind?: string;
    version: string;
}

/**
 * A collection of values returned by getSessionRecordingConfig.
 */
export interface GetSessionRecordingConfigResult {
    readonly id: string;
    readonly kind: string;
    readonly metadata?: outputs.GetSessionRecordingConfigMetadata;
    readonly spec?: outputs.GetSessionRecordingConfigSpec;
    readonly subKind?: string;
    readonly version: string;
}
export function getSessionRecordingConfigOutput(args: GetSessionRecordingConfigOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetSessionRecordingConfigResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("teleport:index/getSessionRecordingConfig:getSessionRecordingConfig", {
        "kind": args.kind,
        "metadata": args.metadata,
        "spec": args.spec,
        "subKind": args.subKind,
        "version": args.version,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSessionRecordingConfig.
 */
export interface GetSessionRecordingConfigOutputArgs {
    kind?: pulumi.Input<string>;
    metadata?: pulumi.Input<inputs.GetSessionRecordingConfigMetadataArgs>;
    spec?: pulumi.Input<inputs.GetSessionRecordingConfigSpecArgs>;
    subKind?: pulumi.Input<string>;
    version: pulumi.Input<string>;
}
