// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getSamlConnector(args: GetSamlConnectorArgs, opts?: pulumi.InvokeOptions): Promise<GetSamlConnectorResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("teleport:index/getSamlConnector:getSamlConnector", {
        "kind": args.kind,
        "metadata": args.metadata,
        "spec": args.spec,
        "subKind": args.subKind,
        "version": args.version,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSamlConnector.
 */
export interface GetSamlConnectorArgs {
    kind?: string;
    metadata?: inputs.GetSamlConnectorMetadata;
    spec: inputs.GetSamlConnectorSpec;
    subKind?: string;
    version: string;
}

/**
 * A collection of values returned by getSamlConnector.
 */
export interface GetSamlConnectorResult {
    readonly id: string;
    readonly kind: string;
    readonly metadata?: outputs.GetSamlConnectorMetadata;
    readonly spec: outputs.GetSamlConnectorSpec;
    readonly subKind?: string;
    readonly version: string;
}
export function getSamlConnectorOutput(args: GetSamlConnectorOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetSamlConnectorResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("teleport:index/getSamlConnector:getSamlConnector", {
        "kind": args.kind,
        "metadata": args.metadata,
        "spec": args.spec,
        "subKind": args.subKind,
        "version": args.version,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSamlConnector.
 */
export interface GetSamlConnectorOutputArgs {
    kind?: pulumi.Input<string>;
    metadata?: pulumi.Input<inputs.GetSamlConnectorMetadataArgs>;
    spec: pulumi.Input<inputs.GetSamlConnectorSpecArgs>;
    subKind?: pulumi.Input<string>;
    version: pulumi.Input<string>;
}
