// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getTrustedDevice(args: GetTrustedDeviceArgs, opts?: pulumi.InvokeOptions): Promise<GetTrustedDeviceResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("teleport:index/getTrustedDevice:getTrustedDevice", {
        "kind": args.kind,
        "metadata": args.metadata,
        "spec": args.spec,
        "version": args.version,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getTrustedDevice.
 */
export interface GetTrustedDeviceArgs {
    kind?: string;
    metadata?: inputs.GetTrustedDeviceMetadata;
    spec?: inputs.GetTrustedDeviceSpec;
    version: string;
}

/**
 * A collection of values returned by getTrustedDevice.
 */
export interface GetTrustedDeviceResult {
    readonly id: string;
    readonly kind: string;
    readonly metadata: outputs.GetTrustedDeviceMetadata;
    readonly spec?: outputs.GetTrustedDeviceSpec;
    readonly version: string;
}
export function getTrustedDeviceOutput(args: GetTrustedDeviceOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetTrustedDeviceResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("teleport:index/getTrustedDevice:getTrustedDevice", {
        "kind": args.kind,
        "metadata": args.metadata,
        "spec": args.spec,
        "version": args.version,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getTrustedDevice.
 */
export interface GetTrustedDeviceOutputArgs {
    kind?: pulumi.Input<string>;
    metadata?: pulumi.Input<inputs.GetTrustedDeviceMetadataArgs>;
    spec?: pulumi.Input<inputs.GetTrustedDeviceSpecArgs>;
    version: pulumi.Input<string>;
}
