// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getTrustedCluster(args: GetTrustedClusterArgs, opts?: pulumi.InvokeOptions): Promise<GetTrustedClusterResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("teleport:index/getTrustedCluster:getTrustedCluster", {
        "kind": args.kind,
        "metadata": args.metadata,
        "spec": args.spec,
        "subKind": args.subKind,
        "version": args.version,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getTrustedCluster.
 */
export interface GetTrustedClusterArgs {
    kind?: string;
    metadata?: inputs.GetTrustedClusterMetadata;
    spec: inputs.GetTrustedClusterSpec;
    subKind?: string;
    version: string;
}

/**
 * A collection of values returned by getTrustedCluster.
 */
export interface GetTrustedClusterResult {
    readonly id: string;
    readonly kind: string;
    readonly metadata?: outputs.GetTrustedClusterMetadata;
    readonly spec: outputs.GetTrustedClusterSpec;
    readonly subKind?: string;
    readonly version: string;
}
export function getTrustedClusterOutput(args: GetTrustedClusterOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetTrustedClusterResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("teleport:index/getTrustedCluster:getTrustedCluster", {
        "kind": args.kind,
        "metadata": args.metadata,
        "spec": args.spec,
        "subKind": args.subKind,
        "version": args.version,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getTrustedCluster.
 */
export interface GetTrustedClusterOutputArgs {
    kind?: pulumi.Input<string>;
    metadata?: pulumi.Input<inputs.GetTrustedClusterMetadataArgs>;
    spec: pulumi.Input<inputs.GetTrustedClusterSpecArgs>;
    subKind?: pulumi.Input<string>;
    version: pulumi.Input<string>;
}
