// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getUser(args: GetUserArgs, opts?: pulumi.InvokeOptions): Promise<GetUserResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("teleport:index/getUser:getUser", {
        "kind": args.kind,
        "metadata": args.metadata,
        "spec": args.spec,
        "status": args.status,
        "subKind": args.subKind,
        "version": args.version,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getUser.
 */
export interface GetUserArgs {
    kind?: string;
    metadata?: inputs.GetUserMetadata;
    spec?: inputs.GetUserSpec;
    status?: inputs.GetUserStatus;
    subKind?: string;
    version: string;
}

/**
 * A collection of values returned by getUser.
 */
export interface GetUserResult {
    readonly id: string;
    readonly kind: string;
    readonly metadata?: outputs.GetUserMetadata;
    readonly spec?: outputs.GetUserSpec;
    readonly status?: outputs.GetUserStatus;
    readonly subKind?: string;
    readonly version: string;
}
export function getUserOutput(args: GetUserOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetUserResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("teleport:index/getUser:getUser", {
        "kind": args.kind,
        "metadata": args.metadata,
        "spec": args.spec,
        "status": args.status,
        "subKind": args.subKind,
        "version": args.version,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getUser.
 */
export interface GetUserOutputArgs {
    kind?: pulumi.Input<string>;
    metadata?: pulumi.Input<inputs.GetUserMetadataArgs>;
    spec?: pulumi.Input<inputs.GetUserSpecArgs>;
    status?: pulumi.Input<inputs.GetUserStatusArgs>;
    subKind?: pulumi.Input<string>;
    version: pulumi.Input<string>;
}
