// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getWorkloadIdentity(args?: GetWorkloadIdentityArgs, opts?: pulumi.InvokeOptions): Promise<GetWorkloadIdentityResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("teleport:index/getWorkloadIdentity:getWorkloadIdentity", {
        "kind": args.kind,
        "metadata": args.metadata,
        "spec": args.spec,
        "subKind": args.subKind,
        "version": args.version,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getWorkloadIdentity.
 */
export interface GetWorkloadIdentityArgs {
    kind?: string;
    metadata?: inputs.GetWorkloadIdentityMetadata;
    spec?: inputs.GetWorkloadIdentitySpec;
    subKind?: string;
    version?: string;
}

/**
 * A collection of values returned by getWorkloadIdentity.
 */
export interface GetWorkloadIdentityResult {
    readonly id: string;
    readonly kind: string;
    readonly metadata?: outputs.GetWorkloadIdentityMetadata;
    readonly spec?: outputs.GetWorkloadIdentitySpec;
    readonly subKind?: string;
    readonly version?: string;
}
export function getWorkloadIdentityOutput(args?: GetWorkloadIdentityOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetWorkloadIdentityResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("teleport:index/getWorkloadIdentity:getWorkloadIdentity", {
        "kind": args.kind,
        "metadata": args.metadata,
        "spec": args.spec,
        "subKind": args.subKind,
        "version": args.version,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getWorkloadIdentity.
 */
export interface GetWorkloadIdentityOutputArgs {
    kind?: pulumi.Input<string>;
    metadata?: pulumi.Input<inputs.GetWorkloadIdentityMetadataArgs>;
    spec?: pulumi.Input<inputs.GetWorkloadIdentitySpecArgs>;
    subKind?: pulumi.Input<string>;
    version?: pulumi.Input<string>;
}
