// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export class Installer extends pulumi.CustomResource {
    /**
     * Get an existing Installer resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: InstallerState, opts?: pulumi.CustomResourceOptions): Installer {
        return new Installer(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'teleport:index/installer:Installer';

    /**
     * Returns true if the given object is an instance of Installer.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Installer {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Installer.__pulumiType;
    }

    /**
     * Kind is the resource kind.
     */
    public readonly kind!: pulumi.Output<string>;
    /**
     * Metadata is the resource metadata.
     */
    public readonly metadata!: pulumi.Output<outputs.InstallerMetadata | undefined>;
    /**
     * Spec is the resource spec.
     */
    public readonly spec!: pulumi.Output<outputs.InstallerSpec>;
    /**
     * SubKind is an optional resource subkind. Currently unused for this resource.
     */
    public readonly subKind!: pulumi.Output<string | undefined>;
    /**
     * Version is the resource version.
     */
    public readonly version!: pulumi.Output<string>;

    /**
     * Create a Installer resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: InstallerArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: InstallerArgs | InstallerState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as InstallerState | undefined;
            resourceInputs["kind"] = state ? state.kind : undefined;
            resourceInputs["metadata"] = state ? state.metadata : undefined;
            resourceInputs["spec"] = state ? state.spec : undefined;
            resourceInputs["subKind"] = state ? state.subKind : undefined;
            resourceInputs["version"] = state ? state.version : undefined;
        } else {
            const args = argsOrState as InstallerArgs | undefined;
            if ((!args || args.spec === undefined) && !opts.urn) {
                throw new Error("Missing required property 'spec'");
            }
            if ((!args || args.version === undefined) && !opts.urn) {
                throw new Error("Missing required property 'version'");
            }
            resourceInputs["kind"] = args ? args.kind : undefined;
            resourceInputs["metadata"] = args ? args.metadata : undefined;
            resourceInputs["spec"] = args ? args.spec : undefined;
            resourceInputs["subKind"] = args ? args.subKind : undefined;
            resourceInputs["version"] = args ? args.version : undefined;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(Installer.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering Installer resources.
 */
export interface InstallerState {
    /**
     * Kind is the resource kind.
     */
    kind?: pulumi.Input<string>;
    /**
     * Metadata is the resource metadata.
     */
    metadata?: pulumi.Input<inputs.InstallerMetadata>;
    /**
     * Spec is the resource spec.
     */
    spec?: pulumi.Input<inputs.InstallerSpec>;
    /**
     * SubKind is an optional resource subkind. Currently unused for this resource.
     */
    subKind?: pulumi.Input<string>;
    /**
     * Version is the resource version.
     */
    version?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a Installer resource.
 */
export interface InstallerArgs {
    /**
     * Kind is the resource kind.
     */
    kind?: pulumi.Input<string>;
    /**
     * Metadata is the resource metadata.
     */
    metadata?: pulumi.Input<inputs.InstallerMetadata>;
    /**
     * Spec is the resource spec.
     */
    spec: pulumi.Input<inputs.InstallerSpec>;
    /**
     * SubKind is an optional resource subkind. Currently unused for this resource.
     */
    subKind?: pulumi.Input<string>;
    /**
     * Version is the resource version.
     */
    version: pulumi.Input<string>;
}
