// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export class OktaImportRule extends pulumi.CustomResource {
    /**
     * Get an existing OktaImportRule resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: OktaImportRuleState, opts?: pulumi.CustomResourceOptions): OktaImportRule {
        return new OktaImportRule(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'teleport:index/oktaImportRule:OktaImportRule';

    /**
     * Returns true if the given object is an instance of OktaImportRule.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is OktaImportRule {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === OktaImportRule.__pulumiType;
    }

    /**
     * Kind is a resource kind
     */
    public readonly kind!: pulumi.Output<string>;
    /**
     * Metadata is resource metadata
     */
    public readonly metadata!: pulumi.Output<outputs.OktaImportRuleMetadata | undefined>;
    /**
     * Spec is the specification for the Okta import rule.
     */
    public readonly spec!: pulumi.Output<outputs.OktaImportRuleSpec>;
    /**
     * SubKind is an optional resource sub kind, used in some resources
     */
    public readonly subKind!: pulumi.Output<string | undefined>;
    /**
     * Version is the API version used to create the resource. It must be specified. Based on this version, Teleport will apply
     * different defaults on resource creation or deletion. It must be an integer prefixed by "v". For example: `v1`
     */
    public readonly version!: pulumi.Output<string>;

    /**
     * Create a OktaImportRule resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: OktaImportRuleArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: OktaImportRuleArgs | OktaImportRuleState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as OktaImportRuleState | undefined;
            resourceInputs["kind"] = state ? state.kind : undefined;
            resourceInputs["metadata"] = state ? state.metadata : undefined;
            resourceInputs["spec"] = state ? state.spec : undefined;
            resourceInputs["subKind"] = state ? state.subKind : undefined;
            resourceInputs["version"] = state ? state.version : undefined;
        } else {
            const args = argsOrState as OktaImportRuleArgs | undefined;
            if ((!args || args.spec === undefined) && !opts.urn) {
                throw new Error("Missing required property 'spec'");
            }
            if ((!args || args.version === undefined) && !opts.urn) {
                throw new Error("Missing required property 'version'");
            }
            resourceInputs["kind"] = args ? args.kind : undefined;
            resourceInputs["metadata"] = args ? args.metadata : undefined;
            resourceInputs["spec"] = args ? args.spec : undefined;
            resourceInputs["subKind"] = args ? args.subKind : undefined;
            resourceInputs["version"] = args ? args.version : undefined;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(OktaImportRule.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering OktaImportRule resources.
 */
export interface OktaImportRuleState {
    /**
     * Kind is a resource kind
     */
    kind?: pulumi.Input<string>;
    /**
     * Metadata is resource metadata
     */
    metadata?: pulumi.Input<inputs.OktaImportRuleMetadata>;
    /**
     * Spec is the specification for the Okta import rule.
     */
    spec?: pulumi.Input<inputs.OktaImportRuleSpec>;
    /**
     * SubKind is an optional resource sub kind, used in some resources
     */
    subKind?: pulumi.Input<string>;
    /**
     * Version is the API version used to create the resource. It must be specified. Based on this version, Teleport will apply
     * different defaults on resource creation or deletion. It must be an integer prefixed by "v". For example: `v1`
     */
    version?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a OktaImportRule resource.
 */
export interface OktaImportRuleArgs {
    /**
     * Kind is a resource kind
     */
    kind?: pulumi.Input<string>;
    /**
     * Metadata is resource metadata
     */
    metadata?: pulumi.Input<inputs.OktaImportRuleMetadata>;
    /**
     * Spec is the specification for the Okta import rule.
     */
    spec: pulumi.Input<inputs.OktaImportRuleSpec>;
    /**
     * SubKind is an optional resource sub kind, used in some resources
     */
    subKind?: pulumi.Input<string>;
    /**
     * Version is the API version used to create the resource. It must be specified. Based on this version, Teleport will apply
     * different defaults on resource creation or deletion. It must be an integer prefixed by "v". For example: `v1`
     */
    version: pulumi.Input<string>;
}
