// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export class Server extends pulumi.CustomResource {
    /**
     * Get an existing Server resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: ServerState, opts?: pulumi.CustomResourceOptions): Server {
        return new Server(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'teleport:index/server:Server';

    /**
     * Returns true if the given object is an instance of Server.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Server {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Server.__pulumiType;
    }

    /**
     * Kind is a resource kind
     */
    public readonly kind!: pulumi.Output<string>;
    /**
     * Metadata is resource metadata
     */
    public readonly metadata!: pulumi.Output<outputs.ServerMetadata>;
    /**
     * Spec is a server spec
     */
    public readonly spec!: pulumi.Output<outputs.ServerSpec | undefined>;
    /**
     * SubKind is an optional resource sub kind, used in some resources
     */
    public readonly subKind!: pulumi.Output<string>;
    /**
     * Version is version
     */
    public readonly version!: pulumi.Output<string>;

    /**
     * Create a Server resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: ServerArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: ServerArgs | ServerState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as ServerState | undefined;
            resourceInputs["kind"] = state ? state.kind : undefined;
            resourceInputs["metadata"] = state ? state.metadata : undefined;
            resourceInputs["spec"] = state ? state.spec : undefined;
            resourceInputs["subKind"] = state ? state.subKind : undefined;
            resourceInputs["version"] = state ? state.version : undefined;
        } else {
            const args = argsOrState as ServerArgs | undefined;
            if ((!args || args.subKind === undefined) && !opts.urn) {
                throw new Error("Missing required property 'subKind'");
            }
            if ((!args || args.version === undefined) && !opts.urn) {
                throw new Error("Missing required property 'version'");
            }
            resourceInputs["kind"] = args ? args.kind : undefined;
            resourceInputs["metadata"] = args ? args.metadata : undefined;
            resourceInputs["spec"] = args ? args.spec : undefined;
            resourceInputs["subKind"] = args ? args.subKind : undefined;
            resourceInputs["version"] = args ? args.version : undefined;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(Server.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering Server resources.
 */
export interface ServerState {
    /**
     * Kind is a resource kind
     */
    kind?: pulumi.Input<string>;
    /**
     * Metadata is resource metadata
     */
    metadata?: pulumi.Input<inputs.ServerMetadata>;
    /**
     * Spec is a server spec
     */
    spec?: pulumi.Input<inputs.ServerSpec>;
    /**
     * SubKind is an optional resource sub kind, used in some resources
     */
    subKind?: pulumi.Input<string>;
    /**
     * Version is version
     */
    version?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a Server resource.
 */
export interface ServerArgs {
    /**
     * Kind is a resource kind
     */
    kind?: pulumi.Input<string>;
    /**
     * Metadata is resource metadata
     */
    metadata?: pulumi.Input<inputs.ServerMetadata>;
    /**
     * Spec is a server spec
     */
    spec?: pulumi.Input<inputs.ServerSpec>;
    /**
     * SubKind is an optional resource sub kind, used in some resources
     */
    subKind: pulumi.Input<string>;
    /**
     * Version is version
     */
    version: pulumi.Input<string>;
}
