// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export class StaticHostUser extends pulumi.CustomResource {
    /**
     * Get an existing StaticHostUser resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: StaticHostUserState, opts?: pulumi.CustomResourceOptions): StaticHostUser {
        return new StaticHostUser(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'teleport:index/staticHostUser:StaticHostUser';

    /**
     * Returns true if the given object is an instance of StaticHostUser.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is StaticHostUser {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === StaticHostUser.__pulumiType;
    }

    /**
     * kind is a resource kind.
     */
    public readonly kind!: pulumi.Output<string>;
    /**
     * metadata is resource metadata.
     */
    public readonly metadata!: pulumi.Output<outputs.StaticHostUserMetadata>;
    /**
     * spec is the static host user spec.
     */
    public readonly spec!: pulumi.Output<outputs.StaticHostUserSpec>;
    /**
     * sub_kind is an optional resource sub kind, used in some resources.
     */
    public readonly subKind!: pulumi.Output<string | undefined>;
    /**
     * version is the resource version. It must be specified. Supported values are: `v2`.
     */
    public readonly version!: pulumi.Output<string>;

    /**
     * Create a StaticHostUser resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: StaticHostUserArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: StaticHostUserArgs | StaticHostUserState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as StaticHostUserState | undefined;
            resourceInputs["kind"] = state ? state.kind : undefined;
            resourceInputs["metadata"] = state ? state.metadata : undefined;
            resourceInputs["spec"] = state ? state.spec : undefined;
            resourceInputs["subKind"] = state ? state.subKind : undefined;
            resourceInputs["version"] = state ? state.version : undefined;
        } else {
            const args = argsOrState as StaticHostUserArgs | undefined;
            if ((!args || args.metadata === undefined) && !opts.urn) {
                throw new Error("Missing required property 'metadata'");
            }
            if ((!args || args.spec === undefined) && !opts.urn) {
                throw new Error("Missing required property 'spec'");
            }
            if ((!args || args.version === undefined) && !opts.urn) {
                throw new Error("Missing required property 'version'");
            }
            resourceInputs["kind"] = args ? args.kind : undefined;
            resourceInputs["metadata"] = args ? args.metadata : undefined;
            resourceInputs["spec"] = args ? args.spec : undefined;
            resourceInputs["subKind"] = args ? args.subKind : undefined;
            resourceInputs["version"] = args ? args.version : undefined;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(StaticHostUser.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering StaticHostUser resources.
 */
export interface StaticHostUserState {
    /**
     * kind is a resource kind.
     */
    kind?: pulumi.Input<string>;
    /**
     * metadata is resource metadata.
     */
    metadata?: pulumi.Input<inputs.StaticHostUserMetadata>;
    /**
     * spec is the static host user spec.
     */
    spec?: pulumi.Input<inputs.StaticHostUserSpec>;
    /**
     * sub_kind is an optional resource sub kind, used in some resources.
     */
    subKind?: pulumi.Input<string>;
    /**
     * version is the resource version. It must be specified. Supported values are: `v2`.
     */
    version?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a StaticHostUser resource.
 */
export interface StaticHostUserArgs {
    /**
     * kind is a resource kind.
     */
    kind?: pulumi.Input<string>;
    /**
     * metadata is resource metadata.
     */
    metadata: pulumi.Input<inputs.StaticHostUserMetadata>;
    /**
     * spec is the static host user spec.
     */
    spec: pulumi.Input<inputs.StaticHostUserSpec>;
    /**
     * sub_kind is an optional resource sub kind, used in some resources.
     */
    subKind?: pulumi.Input<string>;
    /**
     * version is the resource version. It must be specified. Supported values are: `v2`.
     */
    version: pulumi.Input<string>;
}
