// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export class WorkloadIdentity extends pulumi.CustomResource {
    /**
     * Get an existing WorkloadIdentity resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: WorkloadIdentityState, opts?: pulumi.CustomResourceOptions): WorkloadIdentity {
        return new WorkloadIdentity(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'teleport:index/workloadIdentity:WorkloadIdentity';

    /**
     * Returns true if the given object is an instance of WorkloadIdentity.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is WorkloadIdentity {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === WorkloadIdentity.__pulumiType;
    }

    /**
     * The kind of resource represented.
     */
    public readonly kind!: pulumi.Output<string>;
    /**
     * Common metadata that all resources share.
     */
    public readonly metadata!: pulumi.Output<outputs.WorkloadIdentityMetadata | undefined>;
    /**
     * The configured properties of the WorkloadIdentity
     */
    public readonly spec!: pulumi.Output<outputs.WorkloadIdentitySpec | undefined>;
    /**
     * Differentiates variations of the same kind. All resources should contain one, even if it is never populated.
     */
    public readonly subKind!: pulumi.Output<string | undefined>;
    /**
     * The version of the resource being represented.
     */
    public readonly version!: pulumi.Output<string | undefined>;

    /**
     * Create a WorkloadIdentity resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: WorkloadIdentityArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: WorkloadIdentityArgs | WorkloadIdentityState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as WorkloadIdentityState | undefined;
            resourceInputs["kind"] = state ? state.kind : undefined;
            resourceInputs["metadata"] = state ? state.metadata : undefined;
            resourceInputs["spec"] = state ? state.spec : undefined;
            resourceInputs["subKind"] = state ? state.subKind : undefined;
            resourceInputs["version"] = state ? state.version : undefined;
        } else {
            const args = argsOrState as WorkloadIdentityArgs | undefined;
            resourceInputs["kind"] = args ? args.kind : undefined;
            resourceInputs["metadata"] = args ? args.metadata : undefined;
            resourceInputs["spec"] = args ? args.spec : undefined;
            resourceInputs["subKind"] = args ? args.subKind : undefined;
            resourceInputs["version"] = args ? args.version : undefined;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(WorkloadIdentity.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering WorkloadIdentity resources.
 */
export interface WorkloadIdentityState {
    /**
     * The kind of resource represented.
     */
    kind?: pulumi.Input<string>;
    /**
     * Common metadata that all resources share.
     */
    metadata?: pulumi.Input<inputs.WorkloadIdentityMetadata>;
    /**
     * The configured properties of the WorkloadIdentity
     */
    spec?: pulumi.Input<inputs.WorkloadIdentitySpec>;
    /**
     * Differentiates variations of the same kind. All resources should contain one, even if it is never populated.
     */
    subKind?: pulumi.Input<string>;
    /**
     * The version of the resource being represented.
     */
    version?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a WorkloadIdentity resource.
 */
export interface WorkloadIdentityArgs {
    /**
     * The kind of resource represented.
     */
    kind?: pulumi.Input<string>;
    /**
     * Common metadata that all resources share.
     */
    metadata?: pulumi.Input<inputs.WorkloadIdentityMetadata>;
    /**
     * The configured properties of the WorkloadIdentity
     */
    spec?: pulumi.Input<inputs.WorkloadIdentitySpec>;
    /**
     * Differentiates variations of the same kind. All resources should contain one, even if it is never populated.
     */
    subKind?: pulumi.Input<string>;
    /**
     * The version of the resource being represented.
     */
    version?: pulumi.Input<string>;
}
