on:
  push:
    branches:
      - main
jobs:
  pulumi:
    permissions:
      # The "id-token: write" permission is required or Machine ID will not be
      # able to authenticate with the cluster.
      id-token: write
      contents: read
    # if you added a workflow name in the previous step, make sure you use the same value her
    name: pulumi-up
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - run: pwd
      - run: wget https://rolesanywhere.amazonaws.com/releases/1.5.0/X86_64/Linux/aws_signing_helper
      - run: chmod +x aws_signing_helper
      - name: Fetch Teleport binaries
        uses: teleport-actions/setup@v1
        with:
          version: 17.4.6
      - run: tbot start --oneshot -c ./action_support/bot.yaml
      - run: openssl x509 -text -in ./svid-out/svid.pem
      - run: mkdir /home/runner/.aws && mv /home/runner/work/mwi-demo-infra/mwi-demo-infra/action_support/aws_config /home/runner/.aws/config
      - uses: pulumi/actions@v6
      - run: pulumi login s3://mwi-demo-infra-iac-state?profile=mwi-demo-manager -v 5
        # with:
        #   stack-name: mwi-demo-infra
        #   work-dir: ./pulumi
        #   cloud-url: 's3://mwi-demo-infra-iac-state?profile=mwi-demo-manager'
        # env:
        #   AWS_PROFILE: mwi-demo-manager